CHILD_HEIGHT = 180
CHILD_WIDTH = 360
CONTENT_CHILD_WINDOW = "ttllj77c"
CONTENT_CHILD_WINDOW_BROWSE_IMAGE_BUTTON = "4cx9aqrg"
CONTENT_CHILD_WINDOW_STATUS_TEXT = "x5iwlc8t"
PRIMARY_WINDOW = "b9pqk6jh"
VIEWPORT_HEIGHT = 200
VIEWPORT_WIDTH = 400
